SELECT  PRCODE.CODE AGENCY_CODE,
        PRCODE.DESCRIPTION AGENCY_NM,
        P.PRODUCTCODE LINE,
        CASE  WHEN TLPPDSTAT.NAME <> 'Bound'
                THEN TLPPDSTAT.NAME
                WHEN TLPPDSTAT.NAME = 'Bound' AND PPD.CANCELLATIONDATE >= TRUNC(PPD.EDITEFFECTIVEDATE) AND PPD.CANCELLATIONDATE < SYSDATE
                THEN 'Canceled'
                WHEN TLPPDSTAT.NAME = 'Bound' AND TRUNC(SYSDATE) >= PPD.PERIODEND
                THEN 'Expired'
                WHEN TLPPDSTAT.NAME = 'Bound' AND TRUNC(SYSDATE) < PPD.PERIODSTART
                THEN 'Scheduled'
                ELSE 'Inforce'
         END STATUS,
         PPD.POLICYNUMBER,
        TRUNC(P.CREATETIME) CREATE_DATE,
        TRUNC(P.UPDATETIME) LAST_UPDATEDATE,
        TRUNC(PPD.EDITEFFECTIVEDATE) EFFECTIVE_DATE,
        PPD.PRIMARYINSUREDNAME INSURED_NM,
        PPD.TERMNUMBER,
        DECODE(PPD.TERMNUMBER,NULL, 'New', 'Renewal')  AS TRANSTYPE,
        LISTAGG(PF.FORMNUMBER, ', ')  WITHIN GROUP (ORDER BY PF.ID) AS FORMNUMBERS
FROM PC_POLICY P INNER JOIN
    PC_POLICYPERIOD PPD ON P.ID = PPD.POLICYID INNER JOIN
    PCTL_POLICYPERIODSTATUS TLPPDSTAT ON PPD.STATUS = TLPPDSTAT.ID INNER JOIN
    PC_PRODUCERCODE PRCODE ON PPD.PRODUCERCODEOFRECORDID = PRCODE.ID INNER JOIN
    PC_UWCOMPANY UW ON PPD.UWCOMPANY = UW.ID LEFT OUTER JOIN
    PCTL_JURISDICTION PTLJ ON PTLJ.ID=PPD.BASESTATE INNER JOIN
    PC_FORM PF ON PF.BRANCHID=PPD.ID
WHERE
    PPD.POLICYNUMBER IS NOT NULL
    AND P.PRODUCTCODE='BP7BusinessOwners'
    AND PF.FormNumber LIKE '%BP0486%'
   -- AND PTLJ.TYPECODE='AZ'
GROUP BY PRCODE.CODE, PRCODE.DESCRIPTION, P.PRODUCTCODE,
CASE  WHEN TLPPDSTAT.NAME <> 'Bound'
                THEN TLPPDSTAT.NAME
                WHEN TLPPDSTAT.NAME = 'Bound' AND PPD.CANCELLATIONDATE >= TRUNC(PPD.EDITEFFECTIVEDATE) AND PPD.CANCELLATIONDATE < SYSDATE
                THEN 'Canceled'
                WHEN TLPPDSTAT.NAME = 'Bound' AND TRUNC(SYSDATE) >= PPD.PERIODEND
                THEN 'Expired'
                WHEN TLPPDSTAT.NAME = 'Bound' AND TRUNC(SYSDATE) < PPD.PERIODSTART
                THEN 'Scheduled'
                ELSE 'Inforce'
         END, PPD.POLICYNUMBER, P.CREATETIME, P.UPDATETIME, EDITEFFECTIVEDATE, PRIMARYINSUREDNAME, TERMNUMBER
ORDER BY PPD.PRIMARYINSUREDNAME, PPD.POLICYNUMBER