with BP7Submissions as (
select  
PP.CREATETIME, PP.PERIODSTART, PP.id as BRANCHID, PP.POLICYID, PP.JOBID, J.JOBNUMBER, PPS.name as POLICY_STATUS, P.PRODUCTCODE,PP.POLICYNUMBER, SUBEXT.name as AGENT_SELECTION,
TLJ.name AS STATE, TLJ.TYPECODE AS STATE_CODE,
case  when TLJ.TYPECODE='AZ' AND PP.PERIODSTART >= TO_DATE ('MAY-05-2019 00:00:00', 'MM-DD-YYYY hh24:mi:ss') 
    then 'TRUE'
    when TLJ.TYPECODE='CA' and PP.PERIODSTART >= TO_DATE ('JAN-01-2022 00:00:00', 'MM-DD-YYYY hh24:mi:ss') 
     then 'TRUE'
      when TLJ.TYPECODE='NV' and PP.PERIODSTART >= TO_DATE ('NOV-01-2018 00:00:00', 'MM-DD-YYYY hh24:mi:ss') 
     then 'TRUE'
      when TLJ.TYPECODE='OR' and PP.PERIODSTART >= TO_DATE ('MAY-05-2019 00:00:00', 'MM-DD-YYYY hh24:mi:ss') 
     then 'TRUE'
      when TLJ.TYPECODE='WA' and PP.PERIODSTART >= TO_DATE ('JAN-01-2022 00:00:00', 'MM-DD-YYYY hh24:mi:ss') 
     then 'TRUE'
   else 'FALSE'
 end IS_BPP,
DBMS_LOB.SUBSTR(PP.SUBMITTOREVIEWORBIND_EXT, 10) as REFER_BIND, PP.TOTALCOSTRPT, PP.TOTALINFORCEPREMIUMRPT_EXT, PP.TOTALPREMIUMRPT, PP.GUIDEDIRPM_EXT, PP.GUIDEDPREMIUM_EXT
, case  when PP.GUIDEDPREMIUM_EXT IS NOT NULL AND PP.TOTALPREMIUMRPT >= (0.95*GUIDEDPREMIUM_EXT) 
     then 'PREM>=0.95*GUIDEDPREM'
    when PP.GUIDEDPREMIUM_EXT is null 
      then 'NOT BPP'
    else 'PREM<0.95*GUIDEDPREM'
  end IS_HABRISK
from  PC_POLICYPERIOD PP inner join PC_JOB J on J.id=PP.JOBID
inner join PCTL_POLICYPERIODSTATUS PPS on PPS.id=PP.STATUS
inner join PC_POLICY P on P.id=PP.POLICYID
INNER JOIN PCTL_JURISDICTION TLJ ON TLJ.ID=PP.BASESTATE
left outer join PCTL_SUBMISSIONTYPES_EXT SUBEXT on P.SUBMISSIONTYPES_EXT=SUBEXT.id 
WHERE PP.SUBMITTOREVIEWORBIND_EXT is not null AND PP.CREATEUSERID = 5403 
),
--LOSSES 
LOSS_HISTORY as (
select LH.POLICYID AS LH_POLICYID, SUM(LH.TOTALINCURRED) AS TOTAL_LOSS_INCURRED from PC_LOSSHISTENTRY LH inner join BP7SUBMISSIONS BP7S on BP7S.POLICYID=LH.POLICYID GROUP BY LH.POLICYID
),
 
--BPP CONTENTS ONLY
BP7BPPCONTENTS as (
select BP7CC.DIRECTTERM1 as BPPCONTENTSCOVERAGE,  
  case  when BP7CC.DIRECTTERM1 <= 500000
                then 'TRUE'
   else 'FALSE'
  end LESS_THAN_EQ_5K,
BP7CC.PATTERNCODE as BPP_CONTENTSPATTERNCODE, BP7CL.BUILDING, BP7CC.BRANCHID as BP7CC_BRANCHID
from PCX_BP7CLASSIFICATIONCOV BP7CC 
inner join PCX_BP7CLASSIFICATION BP7CL on BP7CC.CLASSIFICATION=BP7CL.id 
inner join BP7SUBMISSIONS BP7S on BP7CC.BRANCHID=BP7S.BRANCHID AND BP7S.BRANCHID=BP7CL.BRANCHID
and BP7CC.PATTERNCODE='BP7ClassificationBusinessPersonalProperty'
),
 
--UMBRELLA POLICIES THAT WERE CREATED USING AP
BP7CULPOL as (
select ULP.BRANCHID as UL_BRANCHID, ULP.POLICYNUMBER as UL_POLICY, ETLCOVOPTION.value as UL_LIMIT,  
case  when ETLCOVOPTION.value <= 4000000
                then 'TRUE'
   else 'FALSE'
  end UL_LESS_THAN_EQ_4M,
BP7S.BRANCHID AS BP7S_BRANCHID
from BP7SUBMISSIONS BP7S 
left outer join PCX_ULPOLICY_CUE ULP on ULP.POLICYNUMBER=BP7S.POLICYNUMBER
left outer join PCX_CUPLINECOV_CUE CULCOV on CULCOV.BRANCHID=ULP.BRANCHID
LEFT OUTER JOIN PC_ETLCOVTERMOPTION ETLCOVOPTION ON CULCOV.CHOICETERM1=ETLCOVOPTION.PATTERNID
),
 
--BPP Building Value ONLY
BP7BUILDINGS as (
select PL.LocationNum, BLDG.BRANCHID as BLDG_BRANCHID, BL.DESCRIPTION, BL.BUILDINGNUM, BLDG.ID AS BLDG_ID
-- Building values
, BP7COV.DIRECTTERM1 as BP7_BUILDING_VALUE
, case  when BP7COV.DIRECTTERM1 <= 6000000
                then 'TRUE'
   else 'FALSE'
  end LESS_THAN_EQ_6M
 
, BP7COV.PATTERNCODE, BP7COV.BRANCHID as BP7COV_BRANCHID, BP7COV.BUILDING 
--e2value
,trc.cost_range_high, trc.cost_range_low, trc.cost_range_med
from PCX_BP7BUILDING  BLDG
inner join PC_BUILDING BL on BLDG.BUILDING=BL.id
inner join PCX_BP7LOCATION BP7L on BLDG.location=BP7L.id
INNER JOIN pc_policylocation PL ON PL.ID=BP7L.LOCATION
inner join BP7SUBMISSIONS BP7S on BLDG.BRANCHID=BP7S.BRANCHID and BP7L.BRANCHID=BP7S.BRANCHID
left outer join PCX_BP7BUILDINGCOV BP7COV on BP7COV.BRANCHID=BP7S.BRANCHID AND BP7COV.BUILDING=BLDG.ID and BP7COV.PATTERNCODE='BP7Structure' 
left outer join PCX_E2VALUE_EXT E2VAL on E2VAL.id=BLDG.E2VALUE_EXT and E2VAL.BRANCHID=BP7S.BRANCHID
left outer join PCX_TOTALREPLACEMENTCOST_EXT TRC on TRC.id=E2VAL.TOTAL_REPLACEMENT_COST and TRC.BRANCHID=BP7S.BRANCHID
ORDER BY PL.ID, BL.ID ASC
),
--
BP7CLASSCODES as (
select 
distinct CLCD.BP7CLASSCODE as BP7CLASSCODE,
BP7CC.DESCRIPTION as BP7CLASSCODEDESC,
BP7S.BRANCHID AS BP7CC_BRANCHID, CLCD.BUILDING AS BP7CC_BUILDING
from BP7SUBMISSIONS BP7S  
LEFT OUTER join PCX_BP7CLASSIFICATION CLCD on CLCD.BRANCHID=BP7S.BRANCHID
left outer join PCX_BP7CLASSCODE BP7CC on CLCD.BP7CLASSCODE=BP7CC.CODE
group by
CLCD.BP7CLASSCODE,
BP7CC.DESCRIPTION,
BP7S.BRANCHID,
CLCD.BUILDING
order by BP7S.BRANCHID
),
 
BP7IRPM as (
select 
 BP7MOD.BRANCHID MOD_BRANCHID,  BP7MOD.PATTERNCODE, SUM(BP7LineRF.ASSESSMENT) as IRPM_PERCENT
from BP7SUBMISSIONS BP7S  
left outer join PCX_BP7LINEMOD BP7MOD on BP7MOD.BRANCHID=BP7S.BRANCHID
left outer join PCX_BP7LINERF BP7LINERF on BP7LINERF.BRANCHID=BP7S.BRANCHID and BP7LINERF.BP7LINEMODIFIER=BP7MOD.id
WHERE BP7MOD.PATTERNCODE='BP7IRPM'
GROUP BY BP7MOD.BRANCHID,BP7MOD.PATTERNCODE
),
 
UWISSUES as (
select  
BP7S.BRANCHID,
--J.JOBNUMBER, 
--PPD.POLICYNUMBER, 
COUNT(UW.id) as NO_OF_RULES
from BP7Submissions BP7S 
left outer join PC_UWISSUE UW on UW.BRANCHID=BP7S.BRANCHID
LEFT OUTER JOIN PC_UWISSUETYPE UWTYPE ON UWTYPE.ID = UW.ISSUETYPEID
group by 
BP7S.BRANCHID
)
 
 
 
select UWI.NO_OF_RULES, BP7S.PERIODSTART, BP7S.JOBNUMBER, BP7S.POLICY_STATUS, BP7S.PRODUCTCODE,BP7S.POLICYNUMBER, BP7S.AGENT_SELECTION,
BP7S.STATE, BP7S.STATE_CODE, BP7S.IS_BPP
, BP7S.REFER_BIND, BP7S.TOTALCOSTRPT, BP7S.TOTALINFORCEPREMIUMRPT_EXT, BP7S.TOTALPREMIUMRPT, BP7S.GUIDEDIRPM_EXT, BP7S.GUIDEDPREMIUM_EXT, BP7S.IS_HABRISK
, LH.TOTAL_LOSS_INCURRED
, BP7B.LocationNum,  BP7B.DESCRIPTION, BP7B.BUILDINGNUM--, BP7B.BLDG_ID, BP7B.BLDG_BRANCHID,
-- Building values
, BP7B.BP7_BUILDING_VALUE, BP7B.LESS_THAN_EQ_6M, BP7B.PATTERNCODE--, BP7B.BP7COV_BRANCHID, BP7B.BUILDING 
--e2value
, BP7B.COST_RANGE_HIGH, BP7B.COST_RANGE_MED,  BP7B.COST_RANGE_LOW
--, CULPOL.UL_BRANCHID
, CULPOL.UL_POLICY, CULPOL.UL_LIMIT,  CULPOL.UL_LESS_THAN_EQ_4M--, CULPOL.BP7S_BRANCHID
, IRPM.PATTERNCODE as IRPM_PATTERNCODE, IRPM.IRPM_PERCENT
, BP7C.BPPCONTENTSCOVERAGE, BP7C.LESS_THAN_EQ_5K, BP7C.BPP_CONTENTSPATTERNCODE
, BP7BCC.BP7CLASSCODE, BP7BCC.BP7CLASSCODEDESC
--, BP7C.* 
from BP7SUBMISSIONS BP7S
left outer join BP7IRPM IRPM on IRPM.MOD_BRANCHID=BP7S.BRANCHID
left outer join BP7CULPOL CULPOL on CULPOL.BP7S_BRANCHID=BP7S.BRANCHID
left outer join LOSS_HISTORY LH on LH.LH_POLICYID=BP7S.POLICYID
left outer join BP7BUILDINGS BP7B on BP7B.BLDG_BRANCHID=BP7S.BRANCHID and BP7B.BP7COV_BRANCHID=BP7S.BRANCHID
left outer join BP7CLASSCODES BP7BCC on BP7BCC.BP7CC_BRANCHID=BP7S.BRANCHID and BP7BCC.BP7CC_BUILDING=BP7B.BLDG_ID
left outer join BP7BPPCONTENTS BP7C on BP7C.BP7CC_BRANCHID=BP7S.BRANCHID and BP7C.BUILDING=BP7B.BLDG_ID
left outer join UWISSUES UWI ON BP7S.BRANCHID=UWI.BRANCHID
--WHERE JOBNUMBER=0012826422
--where BP7S.IS_BPP='TRUE'
ORDER BY BP7S.PERIODSTART
 
;
