WITH AGENCIES AS (
SELECT ORG.NAME, PR.ID AS PRODUCERCODE_ID, PR.CODE, TLDS.NAME as DOMICILE_STATE, TLCO.NAME AS CONTACT_STATE FROM
PC_PRODUCERCODE@PCPROD_ANALYTICS_LINK_USER PR 
INNER JOIN pcx_domicilestateext@PCPROD_ANALYTICS_LINK_USER DS ON DS.PRODUCERCODE=PR.ID
INNER JOIN pctl_state@PCPROD_ANALYTICS_LINK_USER TLDS ON TLDS.ID=DS.STATE
INNER JOIN pc_organization@PCPROD_ANALYTICS_LINK_USER ORG ON ORG.ID=PR.ORGANIZATIONID
INNER JOIN pc_contact@PCPROD_ANALYTICS_LINK_USER CO ON CO.ID=ORG.CONTACTID
INNER JOIN pctl_state@PCPROD_ANALYTICS_LINK_USER TLCO ON TLCO.ID=CO.STATE
)
, POLICIES AS (
SELECT PP.POLICYNUMBER, AG.NAME AS AGENCY_NAME, AG.CODE AS PRODUCER_CODE, AG.DOMICILE_STATE, AG.CONTACT_STATE  
FROM PC_POLICYPERIOD@PCPROD_ANALYTICS_LINK_USER PP 
INNER JOIN PC_POLICY@PCPROD_ANALYTICS_LINK_USER P ON P.ID=PP.POLICYID
inner join PC_POLICYTERM@PCPROD_ANALYTICS_LINK_USER PT on P.id=PT.POLICYID AND PT.MOSTRECENTTERM=1
INNER JOIN PC_PRODUCERCODE@PCPROD_ANALYTICS_LINK_USER PR ON PR.ID = PP.PRODUCERCODEOFRECORDID AND PP.MOSTRECENTMODEL=1
INNER JOIN AGENCIES AG ON AG.PRODUCERCODE_ID = PR.ID)
SELECT * FROM POLICIES
WHERE DOMICILE_STATE <> CONTACT_STATE;