--------------------------------------------------------
--  DDL for Table DAILY_CC_ADDRESS
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_ADDRESS" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"OBFUSCATEDINTERNAL" CHAR(1 BYTE), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"BATCHGEOCODE" CHAR(1 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"ADDRESSLINE1" VARCHAR2(80 BYTE), 
	"ADDRESSLINE2" VARCHAR2(80 BYTE), 
	"COUNTY" VARCHAR2(60 BYTE), 
	"ADDRESSLINE3" VARCHAR2(80 BYTE), 
	"SPATIALPOINT" "SDO_GEOMETRY", 
	"CITYKANJI" VARCHAR2(60 BYTE), 
	"ADDRESSLINE2KANJI" VARCHAR2(80 BYTE), 
	"STATE" NUMBER(22,0), 
	"ADDRESSBOOKUID" VARCHAR2(64 BYTE), 
	"UPDATETIME" TIMESTAMP (6), 
	"COUNTRY" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"EXTERNALLINKID" VARCHAR2(64 BYTE), 
	"CREATEUSERID" NUMBER(22,0), 
	"VALIDUNTIL" TIMESTAMP (6), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"CITYDENORM" VARCHAR2(60 BYTE), 
	"RETIRED" NUMBER(22,0), 
	"CITY" VARCHAR2(60 BYTE), 
	"ADDRESSTYPE" NUMBER(22,0), 
	"ADDRESSLINE1KANJI" VARCHAR2(80 BYTE), 
	"UPDATEUSERID" NUMBER(22,0), 
	"CEDEXBUREAU" VARCHAR2(2 BYTE), 
	"GEOCODESTATUS" NUMBER(22,0), 
	"POSTALCODEDENORM" VARCHAR2(60 BYTE), 
	"CEDEX" CHAR(1 BYTE), 
	"POSTALCODE" VARCHAR2(60 BYTE), 
	"SUBTYPE" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 VARRAY "SPATIALPOINT"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
  ( TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 VARRAY "SPATIALPOINT"."SDO_ORDINATES" STORE AS SECUREFILE LOB 
  ( TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  --------------------------------------------------------
--  DDL for Table DAILY_CC_CATASTROPHE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_CATASTROPHE" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"CATASTROPHEVALIDFROM" TIMESTAMP (6), 
	"SCHEDULEBATCH" CHAR(1 BYTE), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"ACTIVE" CHAR(1 BYTE), 
	"TOPLEFTLATITUDE" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"NAME" VARCHAR2(60 BYTE), 
	"PCSCATASTROPHENUMBER" VARCHAR2(60 BYTE), 
	"TOPLEFTLONGITUDE" NUMBER(22,0), 
	"CATASTROPHEVALIDTO" TIMESTAMP (6), 
	"UPDATETIME" TIMESTAMP (6), 
	"ID" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"POLICYEFFECTIVEDATE" TIMESTAMP (6), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"POLICYRETRIEVALCOMPLETIONTIME" TIMESTAMP (6), 
	"CATASTROPHENUMBER" VARCHAR2(60 BYTE), 
	"POLICYRETRIEVALSETTIME" TIMESTAMP (6), 
	"UPDATEUSERID" NUMBER(22,0), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"TYPE" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"BOTTOMRIGHTLATITUDE" NUMBER(22,0), 
	"BOTTOMRIGHTLONGITUDE" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_CHECK
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_CHECK" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"ISSUEDATE" TIMESTAMP (6), 
	"INSTANTPMTCELLPHONEEXTENSION" VARCHAR2(60 BYTE), 
	"DATEOFSERVICE" TIMESTAMP (6), 
	"UPDATETIME" TIMESTAMP (6), 
	"ISPRIMARY" CHAR(1 BYTE), 
	"SERVICEPDSTART" TIMESTAMP (6), 
	"INSTANTPMTPAYEECELLPHONE" VARCHAR2(30 BYTE), 
	"ID" NUMBER(22,0), 
	"PENDESCALATIONFORBULK" CHAR(1 BYTE), 
	"DEDUCTIONTYPE" NUMBER(22,0), 
	"PAYTODENORM" VARCHAR2(255 BYTE), 
	"CREATEUSERID" NUMBER(22,0), 
	"PAYTO" VARCHAR2(255 BYTE), 
	"ISCOMBINEDCHECK_SP" CHAR(1 BYTE), 
	"MAILINGADDRESSID" NUMBER(22,0), 
	"RECURRINGCHECKID" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"BANKACCOUNTTYPE" NUMBER(22,0), 
	"CHECKINSTRUCTIONS" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"INVOICENUMBER" VARCHAR2(255 BYTE), 
	"BULKINVOICEITEMINFOID" NUMBER(22,0), 
	"ACCOUNTNAME" VARCHAR2(100 BYTE), 
	"MEMO" VARCHAR2(255 BYTE), 
	"VOIDSTOPUSERID" NUMBER(22,0), 
	"INSTANTPMTEXTERNALID" VARCHAR2(255 BYTE), 
	"PORTIONID" NUMBER(22,0), 
	"CHECKTYPE" NUMBER(22,0), 
	"MAILTOADDRESS" VARCHAR2(255 BYTE), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"ENTEREDTIME" TIMESTAMP (6), 
	"BANKNAME" VARCHAR2(100 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"INSTANTPMTVENDORSTATUS" VARCHAR2(255 BYTE), 
	"CHECKNUMBER" VARCHAR2(255 BYTE), 
	"SERVICEPDEND" TIMESTAMP (6), 
	"BANKROUTINGNUMBER" VARCHAR2(20 BYTE), 
	"DELIVERYMETHOD" NUMBER(22,0), 
	"CLAIMID" NUMBER(22,0), 
	"GROUPID" NUMBER(22,0), 
	"INSTANTPMTCELLPHONECOUNTRY" NUMBER(22,0), 
	"INSTANTPMTVENDORSTATUSDESC" VARCHAR2(1333 BYTE), 
	"SCHEDULEDSENDDATE" TIMESTAMP (6), 
	"REPORTABLEAMOUNT" NUMBER(22,0), 
	"PAYMENTMETHOD" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"INSTANTPMTPAYEEEMAIL" VARCHAR2(60 BYTE), 
	"STATUSUPDTONAFTERISSUED_EXT" TIMESTAMP (6), 
	"CHECKBATCHING" NUMBER(22,0), 
	"BANKACCOUNT" NUMBER(22,0), 
	"MAILTO" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(22,0), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"CHECKSETID" NUMBER(22,0), 
	"REPORTABILITY" NUMBER(22,0), 
	"COMBINEDCHECK_SP" NUMBER(22,0), 
	"BANKACCOUNTNUMBER" VARCHAR2(40 BYTE), 
	"REASONFORVOIDSTOP_EXT" NUMBER(22,0), 
	"CLAIMCONTACTID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DAILY_CC_CLAIM
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_CLAIM" 
   (	"REPORTEDDATE" TIMESTAMP (6), 
	"MAINCONTACTTYPE" NUMBER(22,0), 
	"DATEFORMGIVENTOEMP" TIMESTAMP (6), 
	"PREVIOUSGROUPID" NUMBER(22,0), 
	"SIULIFECYCLESTATE" NUMBER(22,0), 
	"SAFETYEQUIPPROV" CHAR(1 BYTE), 
	"FLAGGEDDATE" TIMESTAMP (6), 
	"EXPOSUREBEGAN" TIMESTAMP (6), 
	"ASSIGNEDBYUSERID" NUMBER(22,0), 
	"DATERPTDTOAGENT" TIMESTAMP (6), 
	"DIAGNOSTICCNSISTNT" CHAR(1 BYTE), 
	"CURRENCY" NUMBER(22,0), 
	"CIVILAUTHORITY_EXT" CHAR(1 BYTE), 
	"DATERPTDTOEMPLOYER" TIMESTAMP (6), 
	"LITIGATIONSTATUS" NUMBER(22,0), 
	"EXPOSUREENDED" TIMESTAMP (6), 
	"PREVIOUSQUEUEID" NUMBER(22,0), 
	"FENCESDAMAGED_EXT" CHAR(1 BYTE), 
	"UPDATETIME" TIMESTAMP (6), 
	"STORAGEBOXNUM" VARCHAR2(10 BYTE), 
	"STATEFILENUMBER" VARCHAR2(20 BYTE), 
	"OTHERRECOVSTATUS" NUMBER(22,0), 
	"DRUGSINVOLVED" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"ISOENABLED" CHAR(1 BYTE), 
	"DATEELIGIBLEFORARCHIVE" TIMESTAMP (6), 
	"FLAGGEDREASON" VARCHAR2(1333 BYTE), 
	"CLAIMTIER" NUMBER(22,0), 
	"EXAMINATIONDATE" TIMESTAMP (6), 
	"CREATEUSERID" NUMBER(22,0), 
	"DEATHDATE" TIMESTAMP (6), 
	"FAULT" NUMBER(22,0), 
	"HOWREPORTED" NUMBER(22,0), 
	"REINSURANCEFLAGGEDSTATUS" NUMBER(22,0), 
	"LOSSCAUSE" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"REOPENDATE" TIMESTAMP (6), 
	"PROGRESS" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"MODIFIEDDUTYAVAIL" CHAR(1 BYTE), 
	"INSURERSENTMPNNOTICE" TIMESTAMP (6), 
	"SEGMENT" NUMBER(22,0), 
	"LOCATIONOFTHEFT" NUMBER(22,0), 
	"STORAGETYPE" NUMBER(22,0), 
	"EMPQUSVALIDITY" NUMBER(22,0), 
	"DATECOMPDCSNDUE" TIMESTAMP (6), 
	"FAULTRATING" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"CLAIMANTRPRTDDATE" TIMESTAMP (6), 
	"ASSIGNEDGROUPID" NUMBER(22,0), 
	"LOSSDATE" TIMESTAMP (6), 
	"SUPPLEMENTALWORKLOADWEIGHT" NUMBER(22,0), 
	"CLAIMSOURCE" NUMBER(22,0), 
	"SIESCALATESIU" NUMBER(22,0), 
	"SALVAGESTATUS" NUMBER(22,0), 
	"FLAGGED" NUMBER(22,0), 
	"COMPUTERSECURITY" CHAR(1 BYTE), 
	"SAFETYEQUIPUSED" CHAR(1 BYTE), 
	"ASSIGNEDQUEUEID" NUMBER(22,0), 
	"STORAGELOCATIONSTATE" NUMBER(22,0), 
	"EMPSENTMPNNOTICE" TIMESTAMP (6), 
	"EMPLOYMENTINJURY" CHAR(1 BYTE), 
	"WORKLOADUPDATED" TIMESTAMP (6), 
	"CLOSEDOUTCOME" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"ISORECEIVEDATE" TIMESTAMP (6), 
	"INSUREDPREMISES" CHAR(1 BYTE), 
	"INJWKRINMPN" TIMESTAMP (6), 
	"PERMISSIONREQUIRED" NUMBER(22,0), 
	"EMPLOYERVALIDITYREASON" VARCHAR2(255 BYTE), 
	"STRATEGY" NUMBER(22,0), 
	"ASSIGNEDUSERID" NUMBER(22,0), 
	"STORAGECATEGORY" NUMBER(22,0), 
	"PTPINMPN" CHAR(1 BYTE), 
	"LOADCOMMANDID" NUMBER(22,0), 
	"STATUTEDATE" TIMESTAMP (6), 
	"INJUREDONPREMISES" CHAR(1 BYTE), 
	"DATEFORMRETBYEMP" TIMESTAMP (6), 
	"INSUREDDENORMID" NUMBER(22,0), 
	"TREATEDPATIENTBFR" CHAR(1 BYTE), 
	"CLAIMNUMBER" VARCHAR2(40 BYTE), 
	"SIESCALATESIUDATE" TIMESTAMP (6), 
	"INCIDENTREPORT" CHAR(1 BYTE), 
	"OFFPREMISESPOWEROUTAGE_EXT" CHAR(1 BYTE), 
	"PREEXDISBLTY" CHAR(1 BYTE), 
	"HOSPITALDAYS" NUMBER(22,0), 
	"POLICEDEPTINFO" VARCHAR2(255 BYTE), 
	"STATE" NUMBER(22,0), 
	"SIUSTATUS" NUMBER(22,0), 
	"DONOTDESTROY" CHAR(1 BYTE), 
	"FIRSTNOTICESUIT" CHAR(1 BYTE), 
	"MOLD" CHAR(1 BYTE), 
	"REOPENEDREASON" NUMBER(22,0), 
	"STATEACKNUMBER" VARCHAR2(20 BYTE), 
	"REPORTEDBYTYPE" NUMBER(22,0), 
	"CLOSEDATE" TIMESTAMP (6), 
	"RETIRED" NUMBER(22,0), 
	"STORAGEDATE" TIMESTAMP (6), 
	"FIREDEPTINFO" VARCHAR2(255 BYTE), 
	"BUILDINGGLASS_EXT" CHAR(1 BYTE), 
	"VALIDATIONLEVEL" NUMBER(22,0), 
	"LOBCODE" NUMBER(22,0), 
	"WORKLOADWEIGHT" NUMBER(22,0), 
	"JURISDICTIONSTATE" NUMBER(22,0), 
	"CONCURRENTEMP" NUMBER(22,0), 
	"DATERPTDTOINSURED" TIMESTAMP (6), 
	"MATERIALWOOD_EXT" CHAR(1 BYTE), 
	"ISOSTATUS" NUMBER(22,0), 
	"WEATHERRELATED" CHAR(1 BYTE), 
	"ISOSENDDATE" TIMESTAMP (6), 
	"OSBUILDINGROOFDAMAGE_EXT" NUMBER(22,0), 
	"LOCATIONCODEID" NUMBER(22,0), 
	"STORAGEVOLUMES" VARCHAR2(10 BYTE), 
	"CATASTROPHEID" NUMBER(22,0), 
	"STORAGEBARCODENUM" VARCHAR2(10 BYTE), 
	"INJUREDREGULARJOB" CHAR(1 BYTE), 
	"DISASTER_EXT" NUMBER(22,0), 
	"CLAIMANTDENORMID" NUMBER(22,0), 
	"LOSSLOCATIONCODE" VARCHAR2(5 BYTE), 
	"BENEFITSSTATUSDCSN" CHAR(1 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"ACCIDENTTYPE" NUMBER(22,0), 
	"POLICYID" NUMBER(22,0), 
	"DWELLINGLARGELOSSPOTENTIAL_EXT" CHAR(1 BYTE), 
	"MANIFESTATIONDATE" TIMESTAMP (6), 
	"FURTHERTREATMENT" CHAR(1 BYTE), 
	"REINSURANCEREPORTABLE" CHAR(1 BYTE), 
	"BUILDINGROOFDAMAGE_EXT" NUMBER(22,0), 
	"PURGEDATE" TIMESTAMP (6), 
	"PREVIOUSUSERID" NUMBER(22,0), 
	"LOSSTYPE" NUMBER(22,0), 
	"ISOKNOWN" CHAR(1 BYTE), 
	"AGENCYID" VARCHAR2(9 BYTE), 
	"HOSPITALDATE" TIMESTAMP (6), 
	"LOSSLOCATIONSPATIALDENORM" "SDO_GEOMETRY", 
	"SHOWMEDICALFIRSTINFO" NUMBER(22,0), 
	"DATECOMPDCSNMADE" TIMESTAMP (6), 
	"LOCKINGCOLUMN" NUMBER(22,0), 
	"CURRENTCONDITIONS" CHAR(1 BYTE), 
	"COVERAGEINQUESTION" CHAR(1 BYTE), 
	"LOSSLOCATIONID" NUMBER(22,0), 
	"WEATHER" NUMBER(22,0), 
	"MMIDATE" TIMESTAMP (6), 
	"CLAIMWORKCOMPID" NUMBER(22,0), 
	"ASSIGNMENTDATE" TIMESTAMP (6), 
	"LARGELOSSNOTIFICATIONSTATUS" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(1333 BYTE), 
	"SISCORE" NUMBER(22,0), 
	"ASSIGNMENTSTATUS" NUMBER(22,0), 
	"HAZARDOUSWASTE" CHAR(1 BYTE), 
	"IVANSKNOWN_EXT" CHAR(1 BYTE), 
	"FENCESIGNDAMAGE_EXT" CHAR(1 BYTE), 
	"BUILDINGVACANT_EXT" CHAR(1 BYTE), 
	"PROPERTYOFOTHERS_EXT" CHAR(1 BYTE), 
	"TENANTIMPROVEMENTS_EXT" CHAR(1 BYTE), 
	"MATERIALSDAMAGED_EXT" VARCHAR2(1333 BYTE), 
	"FARMEQUIPMENT_EXT" CHAR(1 BYTE), 
	"FARMOSBUILDINGROOFDAMAGE_EXT" NUMBER(22,0), 
	"LARGELOSSTHRESHOLDVALUE_EXT" NUMBER(22,0), 
	"NOSUBROCOMMENT_EXT" VARCHAR2(255 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 VARRAY "LOSSLOCATIONSPATIALDENORM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
  ( TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 VARRAY "LOSSLOCATIONSPATIALDENORM"."SDO_ORDINATES" STORE AS SECUREFILE LOB 
  ( TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DAILY_CC_CLAIMCONTACT
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_CLAIMCONTACT" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"PERSONFIRSTNAMEDENORM" VARCHAR2(80 BYTE), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"CONTACTVALIDFROM" TIMESTAMP (6), 
	"CREATETIME" TIMESTAMP (6), 
	"POLICYID" NUMBER(22,0), 
	"BENEFITENDDATE" TIMESTAMP (6), 
	"UPDATETIME" TIMESTAMP (6), 
	"CONTACTVALIDTO" TIMESTAMP (6), 
	"CLAIMANTFLAG" CHAR(1 BYTE), 
	"CLAIMID" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"CONTACTPROHIBITED" CHAR(1 BYTE), 
	"ESSENTIALSERVICETYPE" NUMBER(22,0), 
	"BENEFITENDREASONTYPE" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"CONTACTNAMEDENORM" VARCHAR2(1024 BYTE), 
	"BENEFITENDREASON" VARCHAR2(255 BYTE), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"PROVIDERTYPE" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"PERSONLASTNAMEDENORM" VARCHAR2(80 BYTE), 
	"SERVICE" VARCHAR2(1333 BYTE), 
	"DEPENDENTTYPE" NUMBER(22,0), 
	"CONTACTID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DAILY_CC_CLAIMCONTACTROLE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_CLAIMCONTACTROLE" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"ACTIVE" CHAR(1 BYTE), 
	"WITNESSSTATEMENTIND" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"COVEREDPARTYTYPE" NUMBER(22,0), 
	"POLICYID" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"EVALUATIONID" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"MATTERID" NUMBER(22,0), 
	"EXPOSUREID" NUMBER(22,0), 
	"WITNESSPOSITION" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"WITNESSPERSPECTIVE" VARCHAR2(100 BYTE), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"INCIDENTID" NUMBER(22,0), 
	"PARTYNUMBER" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"ROLE" NUMBER(22,0), 
	"NEGOTIATIONID" NUMBER(22,0), 
	"CLAIMCONTACTID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DAILY_CC_CONTACT
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_CONTACT" 
   (	"COMBINEDCHECKFREQ_SP" NUMBER(22,0), 
	"FAXPHONECOUNTRY" NUMBER(22,0), 
	"TAXID" VARCHAR2(60 BYTE), 
	"NAMEDENORM" VARCHAR2(1024 BYTE), 
	"CAREOF_EXT" VARCHAR2(255 BYTE), 
	"COMBINEDCHECKDOW_SP" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"ID" NUMBER(22,0), 
	"ADJUDICATORLICENSE" VARCHAR2(30 BYTE), 
	"LAWFIRMSPECIALTY" NUMBER(22,0), 
	"LASTNAMEDENORM" VARCHAR2(80 BYTE), 
	"LASTNAME" VARCHAR2(80 BYTE), 
	"CREATEUSERID" NUMBER(22,0), 
	"POLICYNUMBERWITHDASHES_EXT" CHAR(1 BYTE), 
	"BEANVERSION" NUMBER(22,0), 
	"VENUETYPE" NUMBER(22,0), 
	"AUTOTOWINGLICENSE" VARCHAR2(30 BYTE), 
	"UPDATEUSERID" NUMBER(22,0), 
	"HOMEPHONEEXTENSION" VARCHAR2(60 BYTE), 
	"SPECIALTYTYPE" NUMBER(22,0), 
	"FIRSTNAME" VARCHAR2(80 BYTE), 
	"W9VALIDFROM" TIMESTAMP (6), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"OCCUPATION" VARCHAR2(80 BYTE), 
	"CELLPHONE" VARCHAR2(30 BYTE), 
	"PRIMARYADDRESSID" NUMBER(22,0), 
	"SUFFIX" NUMBER(22,0), 
	"ADDRESSBOOKUID" VARCHAR2(64 BYTE), 
	"EMAILADDRESS1" VARCHAR2(60 BYTE), 
	"EMAILADDRESS2" VARCHAR2(60 BYTE), 
	"PRIMARYLANGUAGE" NUMBER(22,0), 
	"NUMDEPENDENTS" NUMBER(22,0), 
	"TAXSTATUS" NUMBER(22,0), 
	"COMBINEDCHECKDOM_SP" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"NAMEKANJI" VARCHAR2(1024 BYTE), 
	"FAXPHONE" VARCHAR2(30 BYTE), 
	"CELLPHONEEXTENSION" VARCHAR2(60 BYTE), 
	"EMPLOYEENUMBER" VARCHAR2(255 BYTE), 
	"SUBTYPE" NUMBER(22,0), 
	"FORMERNAME" VARCHAR2(80 BYTE), 
	"LOADCOMMANDID" NUMBER(22,0), 
	"PREFERRED" CHAR(1 BYTE), 
	"OBFUSCATEDINTERNAL" CHAR(1 BYTE), 
	"VENDORTYPE" NUMBER(22,0), 
	"W9RECEIVED" CHAR(1 BYTE), 
	"PARTICLE" VARCHAR2(80 BYTE), 
	"EMPLOYEESECURITYID" VARCHAR2(15 BYTE), 
	"DOINGBUSINESSAS_EXT" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(1024 BYTE), 
	"MEDICALLICENSE" VARCHAR2(30 BYTE), 
	"VENDORNUMBER" VARCHAR2(60 BYTE), 
	"DONOTDESTROY" CHAR(1 BYTE), 
	"PREFERREDCURRENCY" NUMBER(22,0), 
	"SCORE" NUMBER(22,0), 
	"PREFIX" NUMBER(22,0), 
	"SSNRELEASEAUTHORIZED" CHAR(1 BYTE), 
	"W9VALIDTO" TIMESTAMP (6), 
	"TAXFILINGSTATUS" NUMBER(22,0), 
	"LASTNAMEKANJI" VARCHAR2(80 BYTE), 
	"GREENCARDNUMBER" VARCHAR2(15 BYTE), 
	"WITHHOLDINGRATE" NUMBER(22,0), 
	"MIDDLENAME" VARCHAR2(80 BYTE), 
	"ATTORNEYLICENSE" VARCHAR2(30 BYTE), 
	"RETIRED" NUMBER(22,0), 
	"JURISDICTIONASSIGNEDID" VARCHAR2(15 BYTE), 
	"TAXEXEMPTIONSENTITLED" NUMBER(22,0), 
	"MEDICALORGSPECIALTY" NUMBER(22,0), 
	"VALIDATIONLEVEL" NUMBER(22,0), 
	"PRIMARYPHONE" NUMBER(22,0), 
	"W9RECEIVEDDATE" TIMESTAMP (6), 
	"FIRSTNAMEDENORM" VARCHAR2(80 BYTE), 
	"COMBINEDCHECKMETHOD_SP" NUMBER(22,0), 
	"ADJUDICATIVEDOMAIN" NUMBER(22,0), 
	"ESTIMATINGPLATFORM_EXT" NUMBER(22,0), 
	"POLICYSYSTEMID" VARCHAR2(256 BYTE), 
	"FIRSTNAMEKANJI" VARCHAR2(80 BYTE), 
	"DOCTORSPECIALTY" NUMBER(22,0), 
	"CLAIMANTIDTYPE" NUMBER(22,0), 
	"NOTES" CLOB, 
	"GENDER" NUMBER(22,0), 
	"NUMDEPENDENTSU18" NUMBER(22,0), 
	"AUTOREPAIRLICENSE" VARCHAR2(30 BYTE), 
	"HOMEPHONECOUNTRY" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"AUTOSYNC" NUMBER(22,0), 
	"CELLPHONECOUNTRY" NUMBER(22,0), 
	"LICENSENUMBER" VARCHAR2(20 BYTE), 
	"VISANUMBER" VARCHAR2(15 BYTE), 
	"ATTN_EXT" VARCHAR2(255 BYTE), 
	"PENDINGLINKMESSAGE" CHAR(1 BYTE), 
	"LOADRELATEDCONTACTS" CHAR(1 BYTE), 
	"DATEOFBIRTH" TIMESTAMP (6), 
	"PASSPORTNUMBER" VARCHAR2(15 BYTE), 
	"PRIMARYLOCALE" NUMBER(22,0), 
	"EDUCATIONLEVEL" VARCHAR2(2 BYTE), 
	"NUMDEPENDENTSU25" NUMBER(22,0), 
	"ATTORNEYSPECIALTY" NUMBER(22,0), 
	"WORKPHONEEXTENSION" VARCHAR2(60 BYTE), 
	"MARITALSTATUS" NUMBER(22,0), 
	"ORGANIZATIONTYPE" NUMBER(22,0), 
	"FAXPHONEEXTENSION" VARCHAR2(60 BYTE), 
	"HOMEPHONE" VARCHAR2(30 BYTE), 
	"LICENSESTATE" NUMBER(22,0), 
	"IVANSINDICATOR_EXT" CHAR(1 BYTE), 
	"WORKPHONECOUNTRY" NUMBER(22,0), 
	"WORKPHONE" VARCHAR2(30 BYTE), 
	"AGENCYDOMICILESTATE_EXT" VARCHAR2(255 BYTE), 
	"COMMUNICATIONPREFEREMAIL_EXT" CHAR(1 BYTE), 
	"COMMUNICATIONPREFERFAX_EXT" CHAR(1 BYTE), 
	"COMMUNICATIONPREFERMAIL_EXT" CHAR(1 BYTE), 
	"VENDORTAXTYPE_EXT" NUMBER(22,0), 
	"VENDORAVAILABILITY_EXT" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("NOTES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_COVERAGE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_COVERAGE" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"NOTES" VARCHAR2(255 BYTE), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"POLICYID" NUMBER(22,0), 
	"REPLACEAGGLIMIT" NUMBER(22,0), 
	"STATE" NUMBER(22,0), 
	"CURRENCY" NUMBER(22,0), 
	"EXPOSURELIMIT" NUMBER(22,0), 
	"EFFECTIVEDATE" TIMESTAMP (6), 
	"DEDUCTIBLE" NUMBER(22,0), 
	"COVERAGEBASIS" NUMBER(22,0), 
	"CLAIMAGGLIMIT" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"CLAIMTYPE_EXT" VARCHAR2(50 BYTE), 
	"ID" NUMBER(22,0), 
	"EXPIRATIONDATE" TIMESTAMP (6), 
	"CREATEUSERID" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"INCIDENTLIMIT" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"COINSURANCE" NUMBER(22,0), 
	"RISKUNITID" NUMBER(22,0), 
	"PERSONAGGLIMIT" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"ASCOVERAGELINE_EXT" NUMBER(22,0), 
	"LIMITSINDICATOR" NUMBER(22,0), 
	"NONMEDAGGLIMIT" NUMBER(22,0), 
	"SUBTYPE" NUMBER(22,0), 
	"TYPE" NUMBER(22,0), 
	"POLICYSYSTEMID" VARCHAR2(256 BYTE), 
	"LINENUMBER_EXT" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_EXPOSURE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_EXPOSURE" 
   (	"COVERAGEID" NUMBER(22,0), 
	"PREVIOUSGROUPID" NUMBER(22,0), 
	"INCIDENTLIMITREACHED" CHAR(1 BYTE), 
	"LOCKED" CHAR(1 BYTE), 
	"ASSIGNEDBYUSERID" NUMBER(22,0), 
	"OTHERCOVGCHOICE" NUMBER(22,0), 
	"DIAGNOSTICCNSISTNT" CHAR(1 BYTE), 
	"PIPCLAIMAGGLIMITREACHED" CHAR(1 BYTE), 
	"PREVIOUSQUEUEID" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"ID" NUMBER(22,0), 
	"EXAMINATIONDATE" TIMESTAMP (6), 
	"VOCBENEFITSID" NUMBER(22,0), 
	"LOSSCATEGORY" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"CREATEDVIA" NUMBER(22,0), 
	"COMPBENEFITSID" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"LIFEPENSIONBENEFITSID" NUMBER(22,0), 
	"REOPENDATE" TIMESTAMP (6), 
	"AVERAGEWEEKLYWAGES" NUMBER(22,0), 
	"PROGRESS" NUMBER(22,0), 
	"PROGRAMVENDOR_EXT" CHAR(1 BYTE), 
	"UPDATEUSERID" NUMBER(22,0), 
	"SEGMENT" NUMBER(22,0), 
	"LASTDAYWORKED" TIMESTAMP (6), 
	"DEPRECIATEDVALUE" NUMBER(22,0), 
	"SSBENEFIT" CHAR(1 BYTE), 
	"PPDBENEFITSID" NUMBER(22,0), 
	"TPDBENEFITSID" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"SECURITYLEVEL" NUMBER(22,0), 
	"DEATHBENEFITSID" NUMBER(22,0), 
	"WCBENEFIT" CHAR(1 BYTE), 
	"ASSIGNEDGROUPID" NUMBER(22,0), 
	"WCPREEXDISBLTY" CHAR(1 BYTE), 
	"SUPPLEMENTALWORKLOADWEIGHT" NUMBER(22,0), 
	"CLAIMID" NUMBER(22,0), 
	"ASSIGNEDQUEUEID" NUMBER(22,0), 
	"METRICLIMITGENERATION" NUMBER(22,0), 
	"STATLINEID" NUMBER(22,0), 
	"BREAKIN" CHAR(1 BYTE), 
	"TEMPLOCATIONID" NUMBER(22,0), 
	"MIRREPORTABLE" NUMBER(22,0), 
	"WORKLOADUPDATED" TIMESTAMP (6), 
	"CLOSEDOUTCOME" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"EXPOSURETIER" NUMBER(22,0), 
	"ISORECEIVEDATE" TIMESTAMP (6), 
	"INCIDENTID" NUMBER(22,0), 
	"NEWEMPDATAID" NUMBER(22,0), 
	"WAGEBENEFIT" CHAR(1 BYTE), 
	"STRATEGY" NUMBER(22,0), 
	"ASSIGNEDUSERID" NUMBER(22,0), 
	"SETTLEDATE" TIMESTAMP (6), 
	"SSDIBENEFITSID" NUMBER(22,0), 
	"LOADCOMMANDID" NUMBER(22,0), 
	"WCPREEXDISBLTYINFO" VARCHAR2(255 BYTE), 
	"TREATEDPATIENTBFR" CHAR(1 BYTE), 
	"PRIOREMPDATAID" NUMBER(22,0), 
	"WAGESTMTSENT" TIMESTAMP (6), 
	"PIPPERSONAGGLIMITREACHED" CHAR(1 BYTE), 
	"STATE" NUMBER(22,0), 
	"HOSPITALDAYS" NUMBER(22,0), 
	"COVERAGESUBTYPE" NUMBER(22,0), 
	"CLAIMORDER" NUMBER(22,0), 
	"REPLACEMENTVALUE" NUMBER(22,0), 
	"REOPENEDREASON" NUMBER(22,0), 
	"LOSSPARTY" NUMBER(22,0), 
	"WCBENEFITSID" NUMBER(22,0), 
	"OTHERCOVERAGEINFO" VARCHAR2(255 BYTE), 
	"CLOSEDATE" TIMESTAMP (6), 
	"RETIRED" NUMBER(22,0), 
	"VALIDATIONLEVEL" NUMBER(22,0), 
	"WORKLOADWEIGHT" NUMBER(22,0), 
	"DAYSINWEEK" NUMBER(22,0), 
	"JURISDICTIONSTATE" NUMBER(22,0), 
	"LOSTPROPERTYTYPE" NUMBER(22,0), 
	"AUTOCARD100_EXT" CHAR(1 BYTE), 
	"ISOSTATUS" NUMBER(22,0), 
	"PTDBENEFITSID" NUMBER(22,0), 
	"ISOSENDDATE" TIMESTAMP (6), 
	"TTDBENEFITSID" NUMBER(22,0), 
	"SSDIELIGIBLE" CHAR(1 BYTE), 
	"EXPOSURELIMITREACHED" CHAR(1 BYTE), 
	"EXPOSURETYPE" NUMBER(22,0), 
	"PIPNONMEDAGGLIMITREACHED" CHAR(1 BYTE), 
	"CLAIMANTDENORMID" NUMBER(22,0), 
	"WAGESTMTRECD" TIMESTAMP (6), 
	"PIPESSLIMITREACHED" CHAR(1 BYTE), 
	"RIAGREEMENTGROUPID" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"RIGROUPSETEXTERNALLY" CHAR(1 BYTE), 
	"FURTHERTREATMENT" CHAR(1 BYTE), 
	"PIPDEATHBENEFITSID" NUMBER(22,0), 
	"RSBENEFITSID" NUMBER(22,0), 
	"PREVIOUSUSERID" NUMBER(22,0), 
	"ISOKNOWN" CHAR(1 BYTE), 
	"CLAIMANTTYPE" NUMBER(22,0), 
	"DISBENEFITSID" NUMBER(22,0), 
	"HOSPITALDATE" TIMESTAMP (6), 
	"PRIMARYCOVERAGE" NUMBER(22,0), 
	"PIPVOCBENEFITSID" NUMBER(22,0), 
	"SETTLEMETHOD" NUMBER(22,0), 
	"CURRENTCONDITIONS" CHAR(1 BYTE), 
	"OTHERCOVERAGE" CHAR(1 BYTE), 
	"CONTACTPERMITTED" CHAR(1 BYTE), 
	"ASSIGNMENTDATE" TIMESTAMP (6), 
	"ASSIGNMENTSTATUS" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_GROUP
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_GROUP" 
   (	"WORLDVISIBLE" CHAR(1 BYTE), 
	"CREATEUSERID" NUMBER(22,0), 
	"SUPERVISORID" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"SECURITYZONEID" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"VALIDATIONLEVEL" NUMBER(22,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"NAMEKANJI" VARCHAR2(100 BYTE), 
	"ORGANIZATIONID" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"LOADFACTOR" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"GROUPTYPE" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_MATTER
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_MATTER" 
   (	"PUNITIVEDAMAGES" CHAR(1 BYTE), 
	"LOADCOMMANDID" NUMBER(22,0), 
	"PREVIOUSGROUPID" NUMBER(22,0), 
	"FIRSTNOTICE" CHAR(1 BYTE), 
	"RISKTYPE" NUMBER(22,0), 
	"ASSIGNEDBYUSERID" NUMBER(22,0), 
	"NAME" VARCHAR2(128 BYTE), 
	"DECLARATORYJGMT" CHAR(1 BYTE), 
	"FINALSETTLECOST" NUMBER(22,0), 
	"SUBRORELATED" CHAR(1 BYTE), 
	"HEARINGROOM" VARCHAR2(32 BYTE), 
	"RESPONSEDUE" TIMESTAMP (6), 
	"PREVIOUSQUEUEID" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"COURTDISTRICT" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"REOPENEDREASON" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"CLOSEDATE" TIMESTAMP (6), 
	"MEDIATIONDATE" TIMESTAMP (6), 
	"PRIMARYCAUSE" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"FILEDATE" TIMESTAMP (6), 
	"VALIDATIONLEVEL" NUMBER(22,0), 
	"RESOLUTION" NUMBER(22,0), 
	"ARBITRATIONDATE" TIMESTAMP (6), 
	"UPDATEUSERID" NUMBER(22,0), 
	"PUNITIVEAMOUNT" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"TRIALDATE" TIMESTAMP (6), 
	"COURTTYPE" NUMBER(22,0), 
	"SUITTYPE" NUMBER(22,0), 
	"RESPONSEFILED" TIMESTAMP (6), 
	"CREATETIME" TIMESTAMP (6), 
	"ASSIGNEDGROUPID" NUMBER(22,0), 
	"VENUERATING" NUMBER(22,0), 
	"FINALLEGALCOST" NUMBER(22,0), 
	"MEDIATIONROOM" VARCHAR2(32 BYTE), 
	"MOTIONSUMMARYJGMT" CHAR(1 BYTE), 
	"METHODSERVED" NUMBER(22,0), 
	"CLAIMID" NUMBER(22,0), 
	"ARBITRATIONROOM" VARCHAR2(32 BYTE), 
	"ROOM" VARCHAR2(32 BYTE), 
	"STRUCTUREDSETTLE" CHAR(1 BYTE), 
	"PREVIOUSUSERID" NUMBER(22,0), 
	"ASSIGNEDQUEUEID" NUMBER(22,0), 
	"DEFENSEAPPTDATE" TIMESTAMP (6), 
	"HEARINGDATE" TIMESTAMP (6), 
	"SERVICEDATE" TIMESTAMP (6), 
	"LEGALSPECIALTY" NUMBER(22,0), 
	"FILINGDATE" TIMESTAMP (6), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"DOCKETNUMBER" VARCHAR2(20 BYTE), 
	"FINALSETTLEDATE" TIMESTAMP (6), 
	"ADDAMNUMAMOUNT" NUMBER(22,0), 
	"ASSIGNEDUSERID" NUMBER(22,0), 
	"SUBROGATIONSUMMARYID" NUMBER(22,0), 
	"ADDAMNUMSPECIFIED" CHAR(1 BYTE), 
	"CASENUMBER" VARCHAR2(128 BYTE), 
	"MATTERCASENUMBER" VARCHAR2(20 BYTE), 
	"ASSIGNMENTDATE" TIMESTAMP (6), 
	"SENTTODEFENSEDATE" TIMESTAMP (6), 
	"MATTERTYPE" NUMBER(22,0), 
	"ASSIGNMENTSTATUS" NUMBER(22,0), 
	"ARBITRATION" CHAR(1 BYTE), 
	"LITGATIONPOSTURE_EXT" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_POLICY
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_POLICY" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"POLICYSUFFIX" VARCHAR2(255 BYTE), 
	"EMPLOYEEINDICATOR_EXT" CHAR(1 BYTE), 
	"TOTALVEHICLES" NUMBER(22,0), 
	"OTHERINSINFO" VARCHAR2(255 BYTE), 
	"INSUREDSICCODE" VARCHAR2(6 BYTE), 
	"CURRENCY" NUMBER(22,0), 
	"DECPOLICY_EXT" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"ID" NUMBER(22,0), 
	"ASSIGNEDRISK" CHAR(1 BYTE), 
	"FINANCIALINTERESTS" VARCHAR2(255 BYTE), 
	"CREATEUSERID" NUMBER(22,0), 
	"SEQUENCE_EXT" NUMBER(22,0), 
	"RETURNTOWORKPRGM" CHAR(1 BYTE), 
	"LEGALNAME_EXT" VARCHAR2(80 BYTE), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"VALIDATIONLEVEL" NUMBER(22,0), 
	"COVERAGEFORM" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"CANCELLATIONDATE" TIMESTAMP (6), 
	"ORIGEFFECTIVEDATE" TIMESTAMP (6), 
	"ACCOUNTNUMBER" VARCHAR2(40 BYTE), 
	"FOREIGNCOVERAGE" CHAR(1 BYTE), 
	"NOTES" VARCHAR2(255 BYTE), 
	"PARTICIPATION" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"WCOTHERSTATES" VARCHAR2(255 BYTE), 
	"VERIFIED" CHAR(1 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"OTHERINSURANCE" CHAR(1 BYTE), 
	"POLICYSOURCE" NUMBER(22,0), 
	"WCSTATES" VARCHAR2(255 BYTE), 
	"RETROACTIVEDATE" TIMESTAMP (6), 
	"EXCESSPOLICYNUMBER_EXT" VARCHAR2(255 BYTE), 
	"EFFECTIVEDATE" TIMESTAMP (6), 
	"REPORTINGDATE" TIMESTAMP (6), 
	"EXPIRATIONDATE" TIMESTAMP (6), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"POLICYTYPE" NUMBER(22,0), 
	"UNDERWRITINGCO" NUMBER(22,0), 
	"STATUS" NUMBER(22,0), 
	"TOTALPROPERTIES" NUMBER(22,0), 
	"POLICYRATINGPLAN" NUMBER(22,0), 
	"CUSTOMERSERVICETIER" NUMBER(22,0), 
	"POLICYNUMBER" VARCHAR2(40 BYTE), 
	"UNDERWRITINGGROUP" NUMBER(22,0), 
	"POLICYSYSTEMPERIODID" NUMBER(22,0), 
	"PRODUCERCODE" VARCHAR2(255 BYTE), 
	"POLICYDEPARTMENT_EXTID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Table DAILY_CC_RITRANSACTION
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_RITRANSACTION" 
   (	"PUBLICID" VARCHAR2(64 BYTE), 
	"REPORTINGAMOUNT" NUMBER(22,0), 
	"COSTTYPE" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"COSTCATEGORY" NUMBER(22,0), 
	"CLAIMAMOUNT" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"CLAIMID" NUMBER(22,0), 
	"CLAIMTOREPORTINGEXCHANGERATE" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"TRANSACTIONSETID" NUMBER(22,0), 
	"EXPOSUREID" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"LIFECYCLESTATE" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"ADJUSTMENT" CHAR(1 BYTE), 
	"UPDATEUSERID" NUMBER(22,0), 
	"STATUS" NUMBER(22,0), 
	"RIAGREEMENT" NUMBER(22,0), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"SUBTYPE" NUMBER(22,0), 
	"RICODINGID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_TRANSACTION" 
   (	"PAYMENTTYPE" NUMBER(22,0), 
	"LOADCOMMANDID" NUMBER(22,0), 
	"MATTER" NUMBER(22,0), 
	"CLOSECLAIM" CHAR(1 BYTE), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"COSTTYPE" NUMBER(22,0), 
	"BOOKINGDATE" TIMESTAMP (6), 
	"CREATETIME" TIMESTAMP (6), 
	"RESERVINGCURRENCY" NUMBER(22,0), 
	"COSTCATEGORY" NUMBER(22,0), 
	"RESERVELINEID" NUMBER(22,0), 
	"CURRENCY" NUMBER(22,0), 
	"RECOVERYCATEGORY" NUMBER(22,0), 
	"UPDATETIME" TIMESTAMP (6), 
	"CLAIMID" NUMBER(22,0), 
	"CLAIMTOREPORTINGEXCHANGERATE" NUMBER(22,0), 
	"RECOVERYCODINGID" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"TRANSACTIONSETID" NUMBER(22,0), 
	"DOESNOTERODERESERVES" CHAR(1 BYTE), 
	"EXPOSUREID" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"CHECKID" NUMBER(22,0), 
	"LIFECYCLESTATE" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"RETIRED" NUMBER(22,0), 
	"PAYERDENORMID" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"STATUS" NUMBER(22,0), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"TRANSTORESERVINGEXCHANGERATE" NUMBER(22,0), 
	"SUBTYPE" NUMBER(22,0), 
	"OBOCLAIMCONTACTID" NUMBER(22,0), 
	"TRANSTOCLAIMEXCHANGERATE" NUMBER(22,0), 
	"CLAIMCONTACTID" NUMBER(22,0), 
	"CLOSEEXPOSURE" CHAR(1 BYTE), 
	"CHECKREFNUM_EXT" VARCHAR2(255 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CC_TRANSACTIONLINEITEM
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CC_TRANSACTIONLINEITEM" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"CREATEUSERID" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"REPORTINGAMOUNT" NUMBER(22,0), 
	"REPORTINGFOREXAMOUNT" NUMBER(22,0), 
	"BEANVERSION" NUMBER(22,0), 
	"ARCHIVEPARTITION" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"RETIRED" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"DEDUCTIBLEID" NUMBER(22,0), 
	"RESERVINGAMOUNT" NUMBER(22,0), 
	"LINECATEGORY" NUMBER(22,0), 
	"CLAIMAMOUNT" NUMBER(22,0), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"UPDATETIME" TIMESTAMP (6), 
	"TRANSACTIONAMOUNT" NUMBER(22,0), 
	"CLAIMFOREXAMOUNT" NUMBER(22,0), 
	"TRANSACTIONID" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"RESERVINGFOREXAMOUNT" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_CLAIMSTATE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_CLAIMSTATE" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_CONTACT
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_CONTACT" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_COSTCATEGORY
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_COSTCATEGORY" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_COSTTYPE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_COSTTYPE" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Table DAILY_CCTL_EXPOSURESTATE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_EXPOSURESTATE" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_LOSSCAUSE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_LOSSCAUSE" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_POLICYTYPE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_POLICYTYPE" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_RECOVERYCATEGORY
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_RECOVERYCATEGORY" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_RITRANSACTION
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_RITRANSACTION" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_STATE
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_STATE" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_TRANSACTION" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCTL_TRANSACTIONSTATUS
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCTL_TRANSACTIONSTATUS" 
   (	"L_EN_US" VARCHAR2(256 BYTE), 
	"PRIORITY" NUMBER(22,0), 
	"TYPECODE" VARCHAR2(50 BYTE), 
	"S_EN_US" NUMBER(22,0), 
	"RETIRED" CHAR(1 BYTE), 
	"NAME" VARCHAR2(256 BYTE), 
	"ID" NUMBER(22,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table DAILY_CCX_POLICYDEPARTMENT_EXT
--------------------------------------------------------

  CREATE TABLE "DATALAKE"."DAILY_CCX_POLICYDEPARTMENT_EXT" 
   (	"LOADCOMMANDID" NUMBER(22,0), 
	"DEPTNAME" VARCHAR2(80 BYTE), 
	"CREATEUSERID" NUMBER(22,0), 
	"PUBLICID" VARCHAR2(64 BYTE), 
	"UPDATETIME" TIMESTAMP (6), 
	"BEANVERSION" NUMBER(22,0), 
	"CREATETIME" TIMESTAMP (6), 
	"RETIRED" NUMBER(22,0), 
	"ID" NUMBER(22,0), 
	"DEPTNUMBER" NUMBER(22,0), 
	"UPDATEUSERID" NUMBER(22,0), 
	"LOAD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

