SELECT owner, index_name, uniqueness ,STATUS
FROM ALL_INDEXES
--WHERE table_name = 'PC_UW_ISSUE_SDESC_PK'
WHERE OWNER = 'PCDMSADMIN' AND INDEX_NAME IN('PCX_MAJORSYSTEM_EXT_PK','PC_FORM_PK','PC_USERGROUPSTATS_PK',
'PCX_DATASOURCEANDVALUE_EXT_PK','PCX_E2VALUE_EXT_PK','PC_UW_ISSUE_SDESC_PK','PC_UWISSUE_PK','PCX_BP7COST_PK',
'PC_LOCATIONANSWER_PK','PC_FORMTEXTDATA_PK','PCX_UNDERWRITINGINSIGHT_EXT_PK','PC_PERIODANSWER_PK','PC_WORKFLOW_PK', 
'PC_ACCOUNT_PK','PC_JOBUSERROLEASSIGN_PK')
ORDER BY index_name;

SELECT * FROM USER_INDEXES WHERE STATUS = 'UNUSABLE';

DECLARE
  v_idx_name VARCHAR2(255);
  v_sql      VARCHAR2(2000);
BEGIN
  FOR v_idx_name IN (
    SELECT index_name
    FROM ALL_INDEXES
    WHERE uniqueness = 'UNIQUE'
      AND status = 'UNUSABLE'
  ) LOOP
    v_sql := 'ALTER INDEX ' || v_idx_name || ' REBUILD';
    DBMS_OUTPUT.PUT_LINE('Rebuilding index: ' || v_idx_name);
    DBMS_SQL.EXECUTE(v_sql);
  END LOOP;
END;
/


SELECT 'PCX_AUTODECISIONREASONDTO_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_AUTODECISIONREASONDTO_EXT" UNION ALL
SELECT 'PCX_BP7BUILDINGCOV' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7BUILDINGCOV" UNION ALL
SELECT 'PCX_BP7COST' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7COST" UNION ALL
SELECT 'PCX_BP7TRANSACTION' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7TRANSACTION" UNION ALL
SELECT 'PCX_BUILDFAX_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BUILDFAX_EXT" UNION ALL
SELECT 'PCX_CA7TRUCK' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7TRUCK" UNION ALL
SELECT 'PCX_CUPCLASSIFICATION_CUE' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CUPCLASSIFICATION_CUE" UNION ALL
SELECT 'PCX_DATASOURCEANDVALUE_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_DATASOURCEANDVALUE_EXT" UNION ALL
SELECT 'PCX_E2VALUE_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_E2VALUE_EXT" UNION ALL
SELECT 'PCX_MAJORSYSTEMS_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_MAJORSYSTEMS_EXT" UNION ALL
SELECT 'PCX_MAJORSYSTEM_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_MAJORSYSTEM_EXT" UNION ALL
SELECT 'PCX_UNDERWRITINGINSIGHT_EXT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_UNDERWRITINGINSIGHT_EXT" UNION ALL
SELECT 'PC_ACCOUNT' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_ACCOUNT" UNION ALL
SELECT 'PC_FORM' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_FORM" UNION ALL
SELECT 'PC_FORMTEXTDATA' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_FORMTEXTDATA" UNION ALL
SELECT 'PC_JOBUSERROLEASSIGN' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_JOBUSERROLEASSIGN" UNION ALL
SELECT 'PC_LOCATIONANSWER' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_LOCATIONANSWER" UNION ALL
SELECT 'PC_PERIODANSWER' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_PERIODANSWER" UNION ALL
SELECT 'PC_POLICY' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_POLICY" UNION ALL
SELECT 'PC_POLICYPERIOD' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_POLICYPERIOD" UNION ALL
SELECT 'PC_POLICYREGISTRY' AS TABLE_NAME,NULL, COUNT(*) FROM "PCDMSADMIN"."PC_POLICYREGISTRY" UNION ALL
SELECT 'PC_USERGROUPSTATS' AS TABLE_NAME, NULL, COUNT(*) FROM "PCDMSADMIN"."PC_USERGROUPSTATS" UNION ALL
SELECT 'PC_USERUIPREFERENCES' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_USERUIPREFERENCES" UNION ALL
SELECT 'PC_UWISSUE' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_UWISSUE" UNION ALL
SELECT 'PC_UW_ISSUE_SDESC' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_UW_ISSUE_SDESC" UNION ALL
SELECT 'PC_WORKFLOW' AS TABLE_NAME, MAX("updatetime"),  COUNT(*) FROM "PCDMSADMIN"."PC_WORKFLOW";


SELECT 'PCX_CA7COMMAUTOLINECOV' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCX_CA7COMMAUTOLINECOV" union all
SELECT 'PCX_CUPTRANSACTION_CUE' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CUPTRANSACTION_CUE" UNION ALL
SELECT 'PCX_CA7TRUCK'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7TRUCK" UNION ALL
SELECT 'PCX_CA7COST' AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7COST" UNION ALL
SELECT 'PCX_CA7TRANSACTION'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7TRANSACTION" UNION ALL
SELECT 'PCX_BP7CLASSIFICATION'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7CLASSIFICATION" UNION ALL
SELECT 'PCX_BP7BUILDING'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7BUILDING" UNION ALL
SELECT 'PC_BUILDING'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_BUILDING" UNION ALL
SELECT 'PCX_BP7BUILDINGCOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7BUILDINGCOV" UNION ALL
SELECT 'PCX_BP7TRANSACTION'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7TRANSACTION" UNION ALL
SELECT 'PC_POLICY'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_POLICY" UNION ALL
SELECT 'PCX_BP7LINECOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7LINECOV" UNION ALL
SELECT 'PCX_BP7LOCATION'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7LOCATION" UNION ALL
SELECT 'PC_POLICYPERIOD'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_POLICYPERIOD" UNION ALL
SELECT 'PCX_BP7CLASSIFICATIONCOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7CLASSIFICATIONCOV" UNION ALL
SELECT 'PCX_BP7BLANKET'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7BLANKET" UNION ALL
SELECT 'PCX_BP7LOCATIONCOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7LOCATIONCOV" UNION ALL
SELECT 'PCX_BP7COST'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_BP7COST" UNION ALL
SELECT 'PCX_CA7JURISDICTION'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7JURISDICTION" UNION ALL
SELECT 'PCX_CA7STATECOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7STATECOV" UNION ALL
SELECT 'PCX_CA7PRIVATEPASSENGERCOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7PRIVATEPASSENGERCOV" UNION ALL
SELECT 'PCX_CA7TRUCKCOV'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7TRUCKCOV" UNION ALL
SELECT 'PC_POLICYLOCATION'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PC_POLICYLOCATION" UNION ALL
SELECT 'PCX_CA7PRIVATEPASSENGER'	AS TABLE_NAME, MAX("updatetime"), COUNT(*) FROM "PCDMSADMIN"."PCX_CA7PRIVATEPASSENGER" 
;
