DECLARE
V_MONTH number := 06;
V_YEAR number := 2022;
V_START_DATE date := TO_DATE('06/01/2022', 'MM/DD/YYYY');
V_END_DATE date := TO_DATE('06/30/2022', 'MM/DD/YYYY');
BEGIN
DBMS_OUTPUT.PUT_LINE('V_START_DATE = ' ||V_START_DATE);
DBMS_OUTPUT.PUT_LINE('V_END_DATE = ' ||V_END_DATE);
INSERT INTO run_date ( 
    run_date, procedure_name,
    start_date, end_date,
    operator_id, start_time, end_time)
VALUES ( seq_run_date.NEXTVAL, 'Pkg_Gwpc_Legacy.sp_insert_rundate',
    V_START_DATE, V_END_DATE,
    USER, SYSDATE, sysdate);
commit;
PKG_MONTHLY_DW_UPDATE.UP_MONTHLY_SUMMARY(V_MONTH,V_YEAR);
PKG_PREMIUM_CEDING.SP_CEDE_PREMIUMS(V_MONTH,V_YEAR);
PKG_POPULATE_DW_SUMMARY.CREATE_NEW_SUMMARY(V_MONTH,V_YEAR);
PKG_UP_DW.SP_UP_DW_MAIN(V_MONTH,V_YEAR);
SP_POPULATE_MONTHLY_CLAIM(V_MONTH,V_YEAR);
SP_POPULATE_MONTHLY_CLAIMANT(V_MONTH,V_YEAR);
SP_POPULATE_MONTHLY_COV(V_MONTH,V_YEAR);
SP_POPULATE_DW_INCURRED_LOSS;
END;
/
Show errors;