INSERT INTO DAILY_CC_COL_ADJUSTER(CLAIM,CAUSE_OF_LOSS,CMS_UNIT,BRANCH,CREATE_ID ,FIRST_MODIFIED,AUDIT_ID ,LAST_MODIFIED                                 
,ADJUSTER_SUPERVISOR,IND_HSB_ADJUSTER,HOME_OFFICE_SUPERVISOR,SETTLEMENT_AUTHORITY,INDEPENDENT_ADJUSTER,ASSIST_ADJUSTER                             
,DATE_ASSIGNED,COVERAGE,STAFF,IND_ADJUSTER_COMPLETED,ASSIST_ADJUSTER_COMPLETED,CLAIMANT,HSB_ADJUSTER,ASSIGNED_DATE                                 
,INCURREDLOSS_DATE,IS_MAILPROCESSED,IS_CAT,AUTHORISED_BY,AUTHORISED_DATE,IA_OPEN_DATE,IA_CLOSE_DATE,SUBRO_DEMAND,AA_OPEN_DATE                                  
,AA_CLOSE_DATE,AUTO_ASSIGNED_DATE,NAWDATEFLAG,ADJ_ISO_INIT_DISPLAY,ADJ_ISO_REPLACE_DISPLAY,SUP_ISO_INIT_DISPLAY                        
,SUP_ISO_REPLACE_DISPLAY,EXPENSE_SETTLEMENT_AUTHORITY,EXPENSE_AUTHORISED_BY,EXPENSE_AUTHORISED_DATE,EXPOSUREID,LOAD_DATE,CLAIM_SOURCE
)
 select DISTINCT C.ID AS CLAIM, TLLC.ID AS CAUSE_OF_LOSS, '' AS CMS_UNIT, '' AS BRANCH,
  CRE.USERNAME AS CREATE_ID,C.CREATETIME AS FIRST_MODIFIED , CRE.USERNAME AS AUDIT_ID , C.UPDATETIME AS LAST_MODIFIED,
  nvl(SPRVUCT.ID,0) as ADJUSTER_SUPERVISOR
          ,'' AS IND_HSB_ADJUSTER,'' AS HOME_OFFICE_SUPERVISOR,'' AS SETTLEMENT_AUTHORITY,
             CTIA.ID AS INDEPENDENT_ADJUSTER,
            '' AS ASSIST_ADJUSTER,'' AS DATE_ASSIGNED, TO_NUMBER(TLCOVSTY.ID) COVERAGE
            , SPRVU.ID AS STAFF,'' AS IND_ADJUSTER_COMPLETED, '' AS ASSIST_ADJUSTER_COMPLETED,CCT.ID AS CLAIMANT
            , '' AS HSB_ADJUSTER, HIS.EVENTTIMESTAMP AS ASSIGNED_DATE,'' AS INCURREDLOSS_DATE
            , '' AS IS_MAILPROCESSED 
            , CASE WHEN CCAT.CATASTROPHENUMBER IS NOT NULL THEN 1 ELSE 0 END AS IS_CAT
            , '' AS AUTHORISED_BY, '' AS AUTHORISED_DATE
            , SRIA.ASSIGNMENTDATE AS IA_OPEN_DATE,
            CASE WHEN SRIA.CLOSEDATE IS NOT NULL
                                THEN SRIA.CLOSEDATE
                                ELSE  SRC.UPDATETIME 
                              END AS IA_CLOSE_DATE 
           , '' AS SUBRO_DEMAND, '' AS AA_OPEN_DATE, '' AS AA_CLOSE_DATE , '' AS AUTO_ASSIGNED_DATE, '' AS NAWDATEFLAG  
           ,'' AS ADJ_ISO_INIT_DISPLAY , '' AS ADJ_ISO_REPLACE_DISPLAY, '' AS SUP_ISO_INIT_DISPLAY
           ,'' AS SUP_ISO_REPLACE_DISPLAY , '' AS EXPENSE_SETTLEMENT_AUTHORITY , '' AS EXPENSE_AUTHORISED_BY
           , '' AS EXPENSE_AUTHORISED_DATE, EX.ID AS EXPOSUREID
           , TR.UPDATETIME AS LOAD_DATE
           , 'CC' AS CLAIM_SOURCE
   from 
   CC_CLAIM@ECIG_TO_CC_LINK C 
   INNER JOIN CC_CLAIMCONTACT@ECIG_TO_CC_LINK  CCT ON CCT.CLAIMID=C.ID AND CCT.RETIRED=0 
   LEFT OUTER JOIN CCTL_LOSSCAUSE@ECIG_TO_CC_LINK TLLC ON TLLC.ID = C.LOSSCAUSE AND TLLC.RETIRED = 0
   INNER JOIN CC_EXPOSURE@ECIG_TO_CC_LINK EX ON EX.CLAIMID=C.ID AND EX.RETIRED=0
   LEFT OUTER JOIN CCTL_COVERAGESUBTYPE@ECIG_TO_CC_LINK TLCOVSTY ON TLCOVSTY.ID=EX.COVERAGESUBTYPE
   INNER JOIN CC_TRANSACTION@ECIG_TO_CC_LINK  TR ON TR.CLAIMID = C.ID AND EX.ID=TR.EXPOSUREID AND TR.RETIRED = 0
   LEFT OUTER JOIN CC_COVERAGE@ECIG_TO_CC_LINK COV ON COV.ID=EX.COVERAGEID AND COV.RETIRED=0
   LEFT OUTER JOIN CC_USER@ECIG_TO_CC_LINK STADJU ON  STADJU.ID = EX.ASSIGNEDUSERID AND STADJU.RETIRED=0
   LEFT OUTER JOIN CC_GROUPUSER@ECIG_TO_CC_LINK SPRVGU ON SPRVGU.USERID=STADJU.ID
   LEFT OUTER JOIN CC_GROUP@ECIG_TO_CC_LINK SPRVG ON SPRVG.ID=SPRVGU.GROUPID AND SPRVG.RETIRED=0 
   LEFT OUTER JOIN CC_USER@ECIG_TO_CC_LINK SPRVU ON  SPRVU.ID = SPRVG.SUPERVISORID  AND SPRVU.RETIRED=0
   LEFT OUTER JOIN CC_CREDENTIAL@ECIG_TO_CC_LINK  CRE ON CRE.ID = SPRVU.CREDENTIALID AND CRE.RETIRED =0
   LEFT OUTER JOIN CC_CONTACT@ECIG_TO_CC_LINK  SPRVUCT ON SPRVUCT.ID = SPRVU.CONTACTID AND SPRVUCT.RETIRED=0
   INNER JOIN CC_SERVICEREQUEST@ECIG_TO_CC_LINK SRIA ON SRIA.CLAIMID=C.ID 
   LEFT OUTER JOIN CC_SERVICEREQUESTCHANGE@ECIG_TO_CC_LINK SRC ON SRC.SERVICEREQUESTID =  SRIA.ID
   INNER JOIN CC_CONTACT@ECIG_TO_CC_LINK CTIA ON CTIA.ID=SRIA.SPECIALISTID AND CTIA.RETIRED=0 
   LEFT OUTER JOIN CC_CATASTROPHE@ECIG_TO_CC_LINK CCAT ON C.CATASTROPHEID = CCAT.ID AND CCAT.RETIRED = 0
   INNER JOIN cc_history@ecig_to_cc_link HIS ON HIS.EXPOSUREID = EX.ID AND HIS.CLAIMID =  C.ID
   LEFT JOIN cctl_historytype@ecig_to_cc_link TLHY ON TLHY.ID = HIS.type AND TLHY.name = 'Assigned'
   ;
   
   
   --------------------------------------------------------
--  DDL for Table DAILY_CC_COL_ADJUSTER
--------------------------------------------------------

  CREATE TABLE "SQA06"."DAILY_CC_COL_ADJUSTER" 
   (	"CC_COL_ADJUSTER" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"CLAIM" NUMBER, 
	"CAUSE_OF_LOSS" NUMBER, 
	"CMS_UNIT" NUMBER, 
	"BRANCH" NUMBER, 
	"CREATE_ID" VARCHAR2(30 BYTE), 
	"FIRST_MODIFIED" DATE, 
	"AUDIT_ID" VARCHAR2(30 BYTE), 
	"LAST_MODIFIED" DATE, 
	"ADJUSTER_SUPERVISOR" NUMBER, 
	"IND_HSB_ADJUSTER" VARCHAR2(50 BYTE), 
	"HOME_OFFICE_SUPERVISOR" NUMBER, 
	"SETTLEMENT_AUTHORITY" FLOAT(126), 
	"INDEPENDENT_ADJUSTER" NUMBER, 
	"ASSIST_ADJUSTER" NUMBER, 
	"DATE_ASSIGNED" DATE, 
	"COVERAGE" NUMBER, 
	"STAFF" NUMBER, 
	"IND_ADJUSTER_COMPLETED" NUMBER, 
	"ASSIST_ADJUSTER_COMPLETED" NUMBER, 
	"CLAIMANT" NUMBER, 
	"HSB_ADJUSTER" NVARCHAR2(100), 
	"ASSIGNED_DATE" DATE, 
	"INCURREDLOSS_DATE" DATE, 
	"IS_MAILPROCESSED" NUMBER, 
	"IS_CAT" NUMBER, 
	"AUTHORISED_BY" VARCHAR2(100 BYTE), 
	"AUTHORISED_DATE" DATE, 
	"IA_OPEN_DATE" DATE, 
	"IA_CLOSE_DATE" DATE, 
	"SUBRO_DEMAND" NUMBER, 
	"AA_OPEN_DATE" DATE, 
	"AA_CLOSE_DATE" DATE, 
	"AUTO_ASSIGNED_DATE" DATE, 
	"NAWDATEFLAG" DATE, 
	"ADJ_ISO_INIT_DISPLAY" NUMBER, 
	"ADJ_ISO_REPLACE_DISPLAY" NUMBER, 
	"SUP_ISO_INIT_DISPLAY" NUMBER, 
	"SUP_ISO_REPLACE_DISPLAY" NUMBER, 
	"EXPENSE_SETTLEMENT_AUTHORITY" FLOAT(126), 
	"EXPENSE_AUTHORISED_BY" VARCHAR2(100 BYTE), 
	"EXPENSE_AUTHORISED_DATE" DATE, 
    "EXPOSUREID" NUMBER,
	"LOAD_DATE" DATE, 
	"CLAIM_SOURCE" VARCHAR2(30 BYTE)
   );
